### ISSUE TITLE
hugo's new classes causes a KeyError

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#13]
**Describe the bug**
Hugo's 01_input_selected_classes.csv has only three columns, while the old classes.csv had six. 

This causes several issues, after changing line 89 in processor.py, I get a KeyError: 2 in line 106 of processor.py.

**Comment by MichielBbal** [comment]
I've tried two things in processor.py:

1) change the function _init_class_map so it reads data from column 0 and 2.

2) change the csv to 6 instead of 3 columns. 

In both situations this results in the following traceback:
Traceback (most recent call last):
  File "capture_mqtt.py", line 121, in <module>
    c.start()
  File "capture_mqtt.py", line 69, in start
    self._process_loop()
  File "capture_mqtt.py", line 93, in _process_loop
    self._sample_rate, self._process_buf)
  File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 97, in get_predictions
    predictions = self._filter_predictions(predictions)
  File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 107, in _filter_predictions
    return sorted(line, key=lambda p: -p[1])
  File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 106, in <genexpr>
    i in top_indices if predictions[0][i] > hit)
KeyError: 2

**Comment by MichielBbal** [comment]
I've closed this, this is not the right issue.
