### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#15]
In about 30% of the cases I get a KeyError.
Can be immediately after start, can also be later on. 

Here is the traceback:
Traceback (most recent call last):
  File "capture_mqtt.py", line 122, in <module>
    c.start()
  File "capture_mqtt.py", line 69, in start
    self._process_loop()
  File "capture_mqtt.py", line 93, in _process_loop
    self._sample_rate, self._process_buf)
  File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 97, in get_predictions
    predictions = self._filter_predictions(predictions)
  File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 107, in _filter_predictions
    return sorted(line, key=lambda p: -p[1])
  File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 106, in <genexpr>
    i in top_indices if predictions[0][i] > hit)
KeyError: 10

**Comment by gmos** [comment]
Michiel: het model komt met key = 10.  Die wordt niet gevonden.  Kennelijk mist er een (of meerdere) regels in je label-file.
Gebeurt alleen als geluid #10 wordt gevonden.

From: Michiel Bontenbal ***@***.***>
Sent: Wednesday, 26 May 2021 18:50
To: sensemakersamsterdam/OpenEars ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sensemakersamsterdam/OpenEars] KeyError (#15)


In about 30% of the cases I get a KeyError.
Can be immediately after start, can also be later on.

Here is the traceback:
Traceback (most recent call last):
File "capture_mqtt.py", line 122, in
c.start()
File "capture_mqtt.py", line 69, in start
self._process_loop()
File "capture_mqtt.py", line 93, in _process_loop
self._sample_rate, self._process_buf)
File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 97, in get_predictions
predictions = self._filter_predictions(predictions)
File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 107, in _filter_predictions
return sorted(line, key=lambda p: -p[1])
File "/home/pi/OpenEars/devicehive-dev/audio/processor.py", line 106, in
i in top_indices if predictions[0][i] > hit)
KeyError: 10

**Comment by MichielBbal** [comment]
Nieuw model/nieuwe classes dus dit issue is niet meer relevant.
