### ISSUE TITLE
KeyError new model (serval04-21-lstm)

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#16]
When I run the new model (serval04-21-lstm) I get the following error: 

[INFO] 2021-07-02 20:51:15,082: Start recording.
['1000', '1', '1.0', '1.0', 'Silence', '1']
['1001', '2', '1.0', '1.0', '556 gunshots', '1']
['1002', '3', '1.0', '1.0', 'Brommer Alarm', '1']
['1003', '4', '1.0', '1.0', 'Brommer', '1']
['1004', '5', '1.0', '1.0', 'Claxons', '1']
['1005', '6', '1.0', '1.0', 'Dichtklappende autodeuren', '1']
['1006', '7', '1.0', '1.0', 'Luide mensen (schreeuwen enz)', '1']
['1007', '8', '1.0', '1.0', 'Motoren', '1']
['1008', '9', '1.0', '1.0', 'Terrasgeluide (stille mensen)', '1']
['1009', '10', '1.0', '1.0', 'Versterkte muziek', '1']
[INFO] 2021-07-02 20:51:30,649: Start processing.
Traceback (most recent call last):
  File "capture_mqtt.py", line 118, in <module>
    c.start()
  File "capture_mqtt.py", line 69, in start
    self._process_loop()
  File "capture_mqtt.py", line 93, in _process_loop
    self._sample_rate, self._process_buf)
  File "/home/pi/git/OpenEars/devicehive-dev/audio/processor.py", line 95, in get_predictions
    features = self._get_features(examples_batch)
  File "/home/pi/git/OpenEars/devicehive-dev/audio/processor.py", line 132, in _get_features
    params.VGGISH_INPUT_TENSOR_NAME)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3656, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3480, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3522, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input_features:0' refers to a Tensor which does not exist. The operation, 'input_features', does not exist in the graph."

So processor.py is refering to params.py and is looking for two params: VVGISH_INPUT_TENSOR_NAME and VVGISHT_OUTPUT_TENSOR_NAME and it is not able to find these. 

@hugokoopmans  are these not part of the model?

**Comment by MichielBbal** [comment]
Foldername is VGGISH and not VVGISH.
